[package]
name = "substrate-test-client"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
generic-test-client = { package = "substrate-generic-test-client", path = "./generic" }
primitives = { package = "substrate-primitives", path = "../primitives" }
runtime = { package = "substrate-test-runtime", path = "../test-runtime", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../sr-primitives" }

[features]
default = [
	"include-wasm-blob",
	"std",
]
std = [
	"runtime/std",
]
# If enabled, the WASM blob is added to the `GenesisConfig`.
include-wasm-blob = [
	"runtime/include-wasm-blob",
]
