[package]
name = "substrate-finality-grandpa"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
fork-tree = { path = "../../core/util/fork-tree" }
futures = "0.1"
log = "0.4"
parking_lot = "0.7.1"
tokio = "0.1.7"
rand = "0.6"
parity-codec = { version = "3.3", features = ["derive"] }
runtime_primitives = { package = "sr-primitives", path = "../sr-primitives" }
consensus_common = { package = "substrate-consensus-common", path = "../consensus/common" }
substrate-primitives = { path = "../primitives" }
substrate-telemetry = { path = "../telemetry" }
serde_json = "1.0"
client = { package = "substrate-client", path = "../client" }
inherents = { package = "substrate-inherents", path = "../../core/inherents" }
network = { package = "substrate-network", path = "../network" }
service = { package = "substrate-service", path = "../service", optional = true }
srml-finality-tracker = { path = "../../srml/finality-tracker" }
fg_primitives = { package = "substrate-finality-grandpa-primitives", path = "primitives" }
grandpa = { package = "finality-grandpa", git = "https://github.com/paritytech/finality-grandpa/", branch = "mod-equivocation-reports", features = ["derive-codec"] }
consensus_safety = { package = "substrate-consensus-safety", path = "../consensus/safety" }
safety-primitives = { package = "substrate-consensus-safety-primitives", path = "../consensus/safety/primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../transaction-pool" }
node-runtime = { path = "../../node/runtime" }

[dev-dependencies]
consensus_common = { package = "substrate-consensus-common", path = "../consensus/common", features = ["test-helpers"] }
network = { package = "substrate-network", path = "../network", features = ["test-helpers"] }
keyring = { package = "substrate-keyring", path = "../keyring" }
test_client = { package = "substrate-test-client", path = "../test-client"}
env_logger = "0.6"

[features]
default = ["service-integration"]
service-integration = ["service"]
