[package]
name = "substrate-consensus-aura"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Aura consensus algorithm for substrate"
edition = "2018"

[dependencies]
primitives = { package = "substrate-primitives", path = "../../primitives" }
runtime_support = { package = "srml-support", path = "../../../srml/support" }
runtime_version = { package = "sr-version", path = "../../sr-version" }
runtime_io = { package = "sr-io", path = "../../sr-io" }
slots = { package = "substrate-consensus-slots", path = "../slots" }
aura_primitives = { package = "substrate-consensus-aura-primitives", path = "primitives" }
inherents = { package = "substrate-inherents", path = "../../inherents" }
srml-consensus = { path = "../../../srml/consensus" }
srml-aura = { path = "../../../srml/aura" }
client = { package = "substrate-client", path = "../../client" }
substrate-telemetry = { path = "../../telemetry" }
consensus_common = { package = "substrate-consensus-common", path = "../common" }
consensus_safety = { package = "substrate-consensus-safety", path = "../safety" }
safety-primitives = { package = "substrate-consensus-safety-primitives", path = "../safety/primitives" }
authorities = { package = "substrate-consensus-authorities", path = "../authorities" }
runtime_primitives = { package = "sr-primitives", path = "../../sr-primitives" }
transaction_pool = { package = "substrate-transaction-pool", path = "../../transaction-pool" }
grandpa = { package = "finality-grandpa", git = "https://github.com/paritytech/finality-grandpa/", branch = "mod-equivocation-reports", features = ["derive-codec"] }
keyring = { package = "substrate-keyring", path = "../../keyring" }
node-runtime = { path = "../../../node/runtime" }
futures = "0.1.17"
tokio = "0.1.7"
parking_lot = "0.8.0"
log = "0.4"
parity-codec = "3.5.1"

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../../keyring" }
substrate-executor = { path = "../../executor" }
network = { package = "substrate-network", path = "../../network", features = ["test-helpers"]}
service = { package = "substrate-service", path = "../../service" }
test_client = { package = "substrate-test-client", path = "../../test-client" }
test_runtime = { package = "substrate-test-runtime", path = "../../test-runtime" }
env_logger = "0.6"
